#' Prepare TechnoSmArt GPS/GPS-UHF(+TDR) data for import into Movebank
#'
#' @param data.dir Filepath to the directory containing all TechnoSmArt data to be
#'  re-formatted. Data must be in .txt and .csv format, the direct (unaltered) result of
#'  processing raw base station .dem or .ard files using the X Manager program. Multiple .txt and .csv
#'  files can exist for each tag, derived from different base station download events. Other
#'  user-generated files should not be placed in this folder. NOTE: This function relies on the
#'  'Set Movebank Compatibility' button being selected during processing in X Manager
#'  (pressure in millibars, date and time in the same column, date format dd/mm/yyyy, time format 0-24).
#' @param default.name Whether the filenames within data.dir are the default filenames (TRUE/FALSE).
#'  This function expects the default filenames generated by the base station, which then become the
#'  .txt and .csv filenames written by X Manager. If you must alter your base station
#'  filenames (e.g. the same tag is deployed on more than one bird), your new
#'  filenames MUST start with the tag ID followed by an underscore. This tag ID must match the
#'  tag ID in your Movebank reference data file. Defaults to TRUE.
#' @param out.dir Filepath to the directory in which to save .csv files of the
#'  Movebank-formatted position data, and TDR data if applicable.
#' @param spcd Four-letter species code to use when generating the .csv filename
#'  for the Movebank-formatted position data, and TDR data if applicable.
#' @param site Colony name/abbreviation (no spaces) to use when generating the
#'  .csv filename for the Movebank-formatted position data, and TDR data if applicable.
#' @param fast.gps Whether fast processing for GPS data only should be used (TRUE/FALSE).
#' TechnoSmArt tags store GPS data only (timestamp, location, altitude, speed, accuracy)
#' in a .txt file, while all temperature, depth, accelerometry, and tag voltage data are stored
#' in a larger .csv file. If the accelerometry sampling rate is high, this file can
#' be large and result in very slow processing. Setting fast.gps to TRUE processes
#' only the gps data from the .txt file, with no tag voltage or tdr data. Defaults to FALSE.
#'
#' @details This function is intended to compile and format TechnoSmArt GPS and GPS-UHF tracking
#'  data from multiple birds tracked from a single site. It processes the raw data
#'  files (.csv file(s) produced from TechnoSmArt base station file(s) (.dem or .ard) using the
#'  X Manager program) into a single file for positional data and a single file for
#'  temperature-depth data. Files are formatted to comply with Movebank's required field names and units.
#'
#'  Note: For users working with burrow nesting species, you may wish to perform
#'  additional data processing to identify where missing locations likely represent
#'  burrow use, utilizing the base station generated metadata files. If you do this,
#'  you would change 'location-lon' and 'location-lat' to the deployment location,
#'  change the 'comments' field to a description of the change you made and why, and
#'  change 'import-marked-outlier' to FALSE.
#'
#' @return Returns an single object if only positional data are present, or a list
#'  of two objects if both positional and temperature-depth data are present. If out.dir,
#'  spcd, and site are specified, the function will save Movebank-formatted .csv file(s) to
#'  the location specified.
#' @export
#' @importFrom utils read.csv read.table write.csv
#' @importFrom dplyr across where everything
#' @importFrom readr read_delim
formatTechnosmartGPS <- function(data.dir, default.names = TRUE, out.dir = NULL, spcd = NULL, site = NULL, fast.gps = FALSE) {

  if(fast.gps == TRUE){

    ## Format positional data only ##

    # Import and merge all '.txt' files

    files <- list.files(path = data.dir, pattern = "*.txt", recursive = T)

    paths <- paste0(data.dir, "/", files)

    dat_list <- lapply(paths, function(path) {
      df <- readr::read_delim(
        path,
        delim = "\t",
        col_names = c(
          "timestamp",
          "location-lat",
          "location-long",
          "height-above-mean-sea-level",
          "ground-speed",
          "gps:satellite-count",
          "gps-hdop",
          "TechnoSmart-signal-quality"
        ),
        show_col_types = FALSE
      )

      # Get tagID

      df$filename <- basename(path)

      if(default.names == TRUE){

        df <- df |> dplyr::mutate(`tag-id` = sub(".*_(\\d+)-.*", "\\1", filename))

      } else {

        df <- df |> dplyr::mutate(`tag-id` = sub("[_ -].*", "", filename))

      }

      df

    })

    pos <- do.call(rbind, dat_list) |>
      dplyr::distinct()

    print(paste('Loaded', length(files), '.txt data file(s) from', length(unique(pos$`tag-id`)), "tag(s)."))
    print("GPS data only. Tag voltage is not included. If required, run with fast.gps = FALSE to access complete dataset.")

    # Warning if tag ID longer than 15 characters (4 digit tag ID plus band number)

    if (any(nchar(pos[['tag-id']]) > 15, na.rm = TRUE)) {
      warning("Column 'tag-id' contains values longer than 15 characters. Did you mean to set default.names = FALSE?")
    }

    # Format for Movebank, remove invalid dates

    pos <- pos |>
      dplyr::filter(substr(timestamp, 1, 10) != "01/01/0001") |>
      dplyr::mutate(`sensor-type` = "GPS",
                    `gps-fix-type-raw` = ifelse(!is.na(`height-above-mean-sea-level`), "3D", "2D"), # Technosmart reports skipped/missed fixes in separate metadata file
                    timestamp = as.character(as.POSIXct(timestamp, format = "%d/%m/%Y %H:%M:%S", tz = "UTC")),
                    `ground-speed` = `ground-speed`/3.6) |>  # m/s, Technosmart in kph
      dplyr::select('sensor-type', 'tag-id',
                    timestamp, 'location-long', 'location-lat',
                    'gps-fix-type-raw', 'gps:satellite-count', 'gps-hdop', 'TechnoSmart-signal-quality',
                    'height-above-mean-sea-level', 'ground-speed') |>
      dplyr::arrange(`tag-id`, timestamp) |>
      dplyr::distinct()

    # Save .csv if required info is provided

    if(!is.null(out.dir) & !is.null(spcd) & !is.null(site)) {

      write.csv(pos, paste0(out.dir, "/posData_", spcd, "_GPS_", site, ".csv"), row.names = F, na = '')

    }

    return(pos)

  } else {

    ## Format both positional and TDR data from .csv (all data) ##

    # Import and merge all '.csv' files, keep distinct, blanks to NA

    files <- list.files(path = data.dir, pattern = "*.csv", recursive = T)

    # Allow either ; or , separator with delim = NULL

    dat <- do.call(rbind, lapply(paste0(data.dir, "/", files),
                                 readr::read_delim, delim = NULL, show_col_types = FALSE, guess_max = 10000)) |>
      dplyr::distinct()

    # Fix tagIDs

    if(default.names == TRUE){

      dat <- dat |> dplyr::mutate(`tag-id` = sub(".*_(\\d+)-.*", "\\1", TagID))

    } else {

      dat <- dat |> dplyr::mutate(`tag-id` = sub("[_ -].*", "", TagID))

    }

    print(paste('Loaded', length(files), '.csv data file(s) from', length(unique(dat$`tag-id`)), "tag(s)."))

    # Warning if tag ID longer than 15 characters (4 digit tag ID plus band number)

    if (any(nchar(dat[['tag-id']]) > 15, na.rm = TRUE)) {
     warning("Column 'tag-id' contains values longer than 15 characters. Did you mean to set default.names == FALSE?")
    }

    # Remove invalid dates
    # Fix datetime format
    # Fill voltage records, group in case first record of voltage is missing

    dat <- dat |>
      dplyr::filter(substr(Timestamp, 1, 10) != "01/01/0001") |>
      dplyr::mutate(Timestamp = as.character(as.POSIXct(Timestamp, format = "%d/%m/%Y %H:%M:%S", tz = "UTC"))) |>
      dplyr::group_by(`tag-id`) |>
      tidyr::fill(`Battery (V)`, .direction = "down") |>
      dplyr::ungroup()


    ## Make positional dataset (no dive data) ##

    # No records for failed/skipped fixes (poor signal, accelerometry-based) - info in separate metadata file for TechnoSmart
    # No off in range of base station setting

    pos <- dat |>
      dplyr::filter(!is.na(`location-lon`))

    # Rename columns and format for Movebank
    # Filter duplicates, sort

    pos <- pos |>
      dplyr::mutate(`sensor-type` = "GPS",
                    `gps-fix-type-raw` = ifelse(!is.na(`height-msl`), "3D", "2D"), # Technosmart reports skipped/missed fixes in separate metadata file
                    timestamp = Timestamp,
                    #`location-lat` = `location-lat`,
                    `location-long` = `location-lon`,
                    `height-above-mean-sea-level` = `height-msl`, # meters
                    `ground-speed` = `ground-speed`/3.6, # m/s, Technosmart in kph
                    `gps:satellite-count` = satellites,
                    `gps-hdop` = hdop,
                    `TechnoSmart-signal-quality` = `signal-strength`, # dB-Hz
                    `tag-voltage` = `Battery (V)`*1000, # mV not volts
      ) |>
      dplyr::select('sensor-type', 'tag-id',
                    timestamp, 'location-long', 'location-lat',
                    'gps-fix-type-raw', 'gps:satellite-count', 'gps-hdop', 'TechnoSmart-signal-quality',
                    'height-above-mean-sea-level', 'ground-speed', 'tag-voltage') |>
      dplyr::arrange(`tag-id`, timestamp) |>
      dplyr::distinct()

    # Save .csv if required info is provided

    if(!is.null(out.dir) & !is.null(spcd) & !is.null(site)) {

      write.csv(pos, paste0(out.dir, "/posData_", spcd, "_GPS_", site, ".csv"), row.names = F, na = '')

    }


    ## Format TDR data if present ##

    # Occurs within same original file as the position data
    # Column for Pressure or Depth may be absent (get one or the other)

    if(("Pressure" %in% names(dat) && !all(is.na(dat$Pressure))) || "Depth" %in% names(dat) && !all(is.na(dat$Depth))){

      # Make basic TDR dataset, start formatting for Movebank

      tdr <- dat |>
        dplyr::filter(dplyr::if_any(c(Pressure, `Temp. (?C)`), ~ !is.na(.))) |> # remove row if all are NA, drops some Activity records, all Accel 0
        dplyr::select(TagID, Timestamp, Activity, Pressure, `Temp. (?C)`) |>    ## Any point in keeping volatage here too?
        dplyr::mutate(`sensor-type` = "TDR",
                      `TechnoSmart-activity` = ifelse('Active' %in% Activity, 'active', 'inactive'),
                      wet = ifelse('Wet' %in% Activity, TRUE, FALSE)) |>
        dplyr::rename(`tag-id` = TagID,
                      timestamp = Timestamp,
                      `external-temperature` = `Temp. (?C)`) |>
        dplyr::arrange(`tag-id`, timestamp)

      # Fix Pressure column for Movebank, if present

      if("Pressure" %in% names(dat)){
        tdr <- tdr |>
          dplyr::rename(`barometric-pressure` = Pressure) |> # hPa (mbar)
          dplyr::select('sensor-type', 'tag-id', timestamp,
                        'barometric-pressure', 'external-temperature',
                        'TechnoSmart-activity', wet)
      }

      # Fix Depth column for Movebank, if present

      if("Depth" %in% names(dat)){
        tdr <- tdr |>
          dplyr::rename(depth = Depth) |> # meters
          dplyr::select('sensor-type', 'tag-id', timestamp,
                        depth, 'external-temperature',
                        'TechnoSmart-activity', wet)
      }

      print(paste("TDR data identified for", length(unique(tdr$`tag-id`)), "tag(s)."))

      if("depth" %in% names(tdr) & !("barometric-pressure" %in% names(tdr))){
        print("Depth data present instead of pressure data. Consider exporting pressure data from X Manager for archiving on Movebank.")
      }

      # Save .csv if required info is provided

      if(!is.null(out.dir) & !is.null(spcd) & !is.null(site)) {

        write.csv(tdr, paste0(out.dir, "/tdrData_", spcd, "_GPS_", site, ".csv"), row.names = F, na = '')

      }

      # Save pos and tdr as a list
      out_list <- list(
        pos = pos,
        tdr = tdr
      )

      return(out_list)

    } else {

      return(pos)

    }

  }

}












